default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development

test:
  <<: *default
  database: db/test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: <%= ENV['DATABASE_URL'] %>
  username: <%= URI.parse(ENV['DATABASE_URL']).user %>
  password: <%= URI.parse(ENV['DATABASE_URL']).password %>
  host: <%= URI.parse(ENV['DATABASE_URL']).host %>
